apiVersion: apps/v1
kind: Deployment
metadata:
  name: brave-world
  labels:
    app: brave-world
    org: orange
spec:
  replicas: 4
  selector:
    matchLabels:
      app: brave-world
  template:
    metadata:
      labels:
        app: brave-world
    spec:
      containers:
      - name: brave-world
        image: supamonk/brave-world:latest
        ports:
        - containerPort: 5000
